### ISSUE TITLE
Provide a sample configuration for sonobuoy. 

### ISSUE THREAD

**Issue by timothysc** [cncf/k8s-conformance#1]
There are some questions about what data we should collect as part of a sonobuoy run.  Ideally we (the k8s-conformance-group) can establish a default set that can be used by another tool to validate.  

For example the default configuration in the quickstart is listed here: https://github.com/heptio/sonobuoy/blob/master/examples/quickstart/10-configmaps.yaml#L23

**Comment by mml** [comment]
I've tried to strip it down as much as possible and am currently using https://gist.github.com/mml/17f94ff8308ba7712e7c40a10da72b6a

That's no resources, only the e2e plugin, and running all the `[Conformance]` tests.

**Comment by WilliamDenniss** [comment]
Resolved in #2
