### ISSUE TITLE
Conformance Test: some [sig-network] tests failed.

### ISSUE THREAD

**Issue by mohjam2004** [cncf/k8s-conformance#1152]
I have run conformance test (by sonobuoy) on my cluster and I have some failures. my kubernetes version is 1.18.3. I have run the tests many times and the result is the same all the time:
Plugin: e2e
Status: failed
Total: 4992
Passed: 266
Failed: 9
Skipped: 4717

Failed tests:
[sig-network] Services should be able to change the type from ClusterIP to ExternalName [Conformance]
[sig-network] DNS should provide DNS for ExternalName services [Conformance]
[sig-network] DNS should provide DNS for services  [Conformance]
[sig-network] DNS should provide DNS for pods for Hostname [LinuxOnly] [Conformance]
[sig-network] Services should be able to change the type from NodePort to ExternalName [Conformance]
[sig-network] DNS should provide /etc/hosts entries for the cluster [LinuxOnly] [Conformance]
[sig-network] DNS should provide DNS for pods for Subdomain [Conformance]
[sig-network] DNS should provide DNS for the cluster  [Conformance]
[sig-network] DNS should resolve DNS of partial qualified names for services [LinuxOnly] [Conformance]

**what can cause these failures?**

![image](https://user-images.githubusercontent.com/59224403/95182607-b7e92000-07d1-11eb-91ea-f4359f410eeb.png)

![image](https://user-images.githubusercontent.com/59224403/95182699-d3ecc180-07d1-11eb-81c2-a3484ce93851.png)

![image](https://user-images.githubusercontent.com/59224403/95182791-eebf3600-07d1-11eb-9613-01be0ea5614b.png)

![image](https://user-images.githubusercontent.com/59224403/95182872-0a2a4100-07d2-11eb-94ff-38d8fdbbfc47.png)

![image](https://user-images.githubusercontent.com/59224403/95182961-2a5a0000-07d2-11eb-8e4d-f528d103e056.png)

![image](https://user-images.githubusercontent.com/59224403/95183026-42318400-07d2-11eb-8d53-dbbf89bce13a.png)

![image](https://user-images.githubusercontent.com/59224403/95183106-5aa19e80-07d2-11eb-8c4f-6b4de8cbc3ed.png)

![image](https://user-images.githubusercontent.com/59224403/95183169-73aa4f80-07d2-11eb-9b30-e218893ba113.png)

![image](https://user-images.githubusercontent.com/59224403/95183228-8b81d380-07d2-11eb-9493-2712f50a2521.png)

**Comment by zenhighzer** [comment]
same here, 

8 x virtualbox-machines, each with two network-adapters (nat and host-only adapter):
- 1 x a dns-server/bind9 dns-lookups in generall are working fine between all vm´s  
- 2 x loadbalancer-vm (haproxy: vip for control-plane-endpoint)
- running 3 x k8s-master-vm, 2 x k8s-worker-vm
- installed via. kubeadm and flannel 


Plugin: e2e
Status: failed
Total: 5771
Passed: 329
Failed: 8
Skipped: 5434

Failed tests:
[sig-network] DNS should resolve DNS of partial qualified names for services [LinuxOnly] [Conformance]
[sig-network] DNS should provide /etc/hosts entries for the cluster [LinuxOnly] [Conformance]
[sig-network] DNS should provide DNS for pods for Hostname [LinuxOnly] [Conformance]
[sig-network] DNS should provide DNS for pods for Subdomain [Conformance]
[sig-network] DNS should provide DNS for the cluster  [Conformance]
[sig-network] DNS should provide DNS for services  [Conformance]
[sig-network] Services should be able to change the type from NodePort to ExternalName [Conformance]
[sig-network] Services should be able to change the type from ClusterIP to ExternalName [Conformance]

Plugin: systemd-logs
Status: passed
Total: 5
Passed: 5
Failed: 0
Skipped: 0

**Comment by mohjam2004** [comment]
hi @zenhighzer 
I think you have changed your default cluster domain name from cluster.local to some thing else.
you shoud run your cluster conformance test with an option switch by whitch you can specify you correct domain name to conformance test.

**Comment by hitorig** [comment]
> hi @zenhighzer I think you have changed your default cluster domain name from cluster.local to some thing else. you shoud run your cluster conformance test with an option switch by whitch you can specify your correct domain name to conformance test. you can find the correct option (to tell the confomance test your correct domain name) from sonobuoy documents.

I set cluster domain name with cluster.local but it did not work

**Comment by Riaankl** [comment]
Stale issue.
Sure we can close after 3 years of no action of follow-up.
