### ISSUE TITLE
Our installer product doesn't have a website yet

### ISSUE THREAD

**Issue by Wenshiqi222** [cncf/k8s-conformance#1533]
We are doing the conformance certification for our product k8s-installer, but we donnot create a website for the product yet,as i know the PRODUCT.yaml file has a "website"  filed ，so can i just skip this filed？

**Comment by ErinThacker** [comment]
@Wenshiqi222 - yes, you can skip this field.

**Comment by Wenshiqi222** [comment]
> @Wenshiqi222 - yes, you can skip this field.

thanks  a lot
