### ISSUE TITLE
After conformance certification, service not displayed in 'Certified Kubernetes - Hosted '.

### ISSUE THREAD

**Issue by ruiyaoOps** [cncf/k8s-conformance#1544]
https://github.com/cncf/k8s-conformance/pull/1504
In pr 1504, I had conformance certification for QKE on 9 Jun, but it was not displayed in 'Certified Kubernetes - Hosted ', why? What can I do?
![image](https://user-images.githubusercontent.com/35256376/126587835-ef03804b-4928-498b-8bea-bfbb736046e7.png)

**Comment by ErinThacker** [comment]
@ruiyaoOps - I'll take a look at this today and get a pull request in today. My apologies for my oversight.

**Comment by ruiyaoOps** [comment]
@ErinThacker I found it in Hosted, thank you very much.
I closed the issue.
