### ISSUE TITLE
Kubernetes Conformance - Expired Certification

### ISSUE THREAD

**Issue by Syulin7** [cncf/k8s-conformance#1555]
we have resubmitted the conformance certification in PR #1534 , but it was not displayed in 'Certified Kubernetes'( https://www.cncf.io/certification/software-conformance/ ). Please take a look.

![image](https://user-images.githubusercontent.com/37265556/127269767-90ba1d81-5c60-4f8a-8d5c-b567b60235c8.png)

**Comment by Syulin7** [comment]
PTAL @ErinThacker

**Comment by Syulin7** [comment]
@taylorwaggoner Please take a look and add to the Cloud Native landscape. Thanks!

**Comment by tizhou86** [comment]
@ErinThacker Please let us know if anything we need to do, thanks!
