### ISSUE TITLE
New output?

### ISSUE THREAD

**Issue by drpaneas** [cncf/k8s-conformance#172]
The output of the tests it used to be sth like:

```bash
Ran 125 of 782 Specs in 2891.461 seconds
SUCCESS! -- 125 Passed | 0 Failed | 0 Pending | 657 Skipped PASS
```

Now we noticed that there are 2 additional lines at the end:

```bash
Ran 125 of 782 Specs in 2877.143 seconds
SUCCESS! -- 125 Passed | 0 Failed | 0 Pending | 657 Skipped PASS

Ginkgo ran 1 suite in 47m57.777851116s
Test Suite Passed
```

I would like to ask you where this string `Test Suite Passed` comes from and if it would be just enough to `grep` for this string to verify a successful test-run.

**Comment by dankohn** [comment]
It is generated by Sonobuoy and it should be fine to grep for that.
