### ISSUE TITLE
What are the plans for 1.10 tests?

### ISSUE THREAD

**Issue by tamalsaha** [cncf/k8s-conformance#185]

**Comment by gyliu513** [comment]
After some test with 1.10.0, 6 cases failed at https://github.com/kubernetes/kubernetes/issues/62517

**Comment by gyliu513** [comment]
Any feedback for this?

**Comment by dankohn** [comment]
https://github.com/cncf/k8s-conformance/tree/master/v1.10/cdk
We've gotten our first v1.10 certification, so it seems feasible. If you're having specific tests fail, especially on vanilla Kubernetes, please open an issue with SIG-testing. (But please also paste the URL here for cross-reference.)

Closing for now, but we can reopen if there systemic issues.

**Comment by gyliu513** [comment]
I have fixed the conformance test issue at https://github.com/cncf/k8s-conformance/pull/194

/cc @dankohn
