### ISSUE TITLE
Can provide alternate image location instead of gcr.io

### ISSUE THREAD

**Issue by jolestar** [cncf/k8s-conformance#20]
As we all know, user can not visit gcr.io in China. So, it is hard to run k8s conformance program.
Can provide alternate image location (e.g.: hub.docker)  and support passing parameters to use alternate image location.
This need to make changes to sonobuoy and e2e.

**Comment by dankohn** [comment]
CNCF isn't in a position to do the development ourselves, but if you or anyone else in China would like to run the necessary endpoint on a cloud in China, we would be happy to cover the cost.

Also, if you submit a pull request to the e2e test framework adding a (non-default) option for using the alternate endpoint, we would advocate for its adoption.

**Comment by timothysc** [comment]
@jolestar you can easily rebuild sonobuoy on your own and push to you your own repo:  https://github.com/heptio/sonobuoy  

The real problem is getting all the e2e containers, b/c they are not a build artifact from the main repository.  I'm going to work with upstream in 1.9 to help support air-gap'd validation. 

/cc @sampowers

**Comment by dankohn** [comment]
9 of the 29 current Certified Kubernetes products are from mainland China, so this doesn't seem to be blocking them. CNCF is working to get an ICP license and Chinese CDN access to kubernetes.io, but it is still months off and wouldn't solve the issues around access to GitHub or container registries.

**Comment by mpw07458** [comment]
Hi, is it possible to reopen this? I am using AWS China cloud with Kubespray and have run into the repo issue, is a workaround to copy the binaries to AWS S3?
