### ISSUE TITLE
Branch protection rules

### ISSUE THREAD

**Issue by BobyMCbobs** [cncf/k8s-conformance#2150]
Today I added status badges for PRs, which you'll notice at the bottom of the PR
<img width="912" alt="Screen Shot 2022-09-05 at 14 39 00" src="https://user-images.githubusercontent.com/8588826/188350309-93cd9f16-15f7-4d8e-beff-ebaef8df3449.png">

While certainly not a requirement, there is now the option to enable branch protection requiring select status checks to be passing before a PR is mergeable.

A pro is that nothing that is definitely not checked and passing can merge.
A con is that if an error were to occur with the bot and a PR was manually verified, it wouldn't be able merged.

Interested to hear thoughts.
Please close if not needed or desired.

/cc @taylorwaggoner @Riaankl

**Comment by taylorwaggoner** [comment]
@BobyMCbobs thanks! Just to clarify, say for example a company used a logo file that had the incorrect format, but I wanted to approve them anyway, I wouldn't be able to do so until they fixed the file format?

**Comment by BobyMCbobs** [comment]
@taylorwaggoner, that is correct

**Comment by BobyMCbobs** [comment]
Of course, at the same time, the bot should be updated to meet your criteria. So the bot could be updated to support the logo in whichever format.

**Comment by BobyMCbobs** [comment]
Some branch protection rules have been added to this repo for the default branch:
- require approval of one
- @taylorwaggoner is able to bypass requirements 
- require DCO check

Unsure about the current best way to ensure that the verify-conformance check is required only for conformance PRs, since some PRs for this repo are not submissions. I know with some Prow related job checks in Kubernetes infra, there's a generic check which is required but whether that passes depends on the state of other jobs which are not required.

**Comment by Riaankl** [comment]
Thank you for updating this @BobyMCbobs
