### ISSUE TITLE
should provide a conformance yaml for cluster with RABC closed

### ISSUE THREAD

**Issue by stewart-yu** [cncf/k8s-conformance#22]
Though command 'curl -L https://raw.githubusercontent.com/cncf/k8s-conformance/master/sonobuoy-conformance-1.7.yaml | kubectl apply -f -' , the result are right, But i think should provide a conformance yaml for cluster RABC closed.

**Comment by WilliamDenniss** [comment]
Let's discuss this at the next meetup.

**Comment by dankohn** [comment]
Closing for now, but @WilliamDenniss will bring up at the meeting at KubeCon.
