### ISSUE TITLE
Tracking issue - Identify API-Machinery e2e tests to be promoted to conformance and evaluate gaps in coverage

### ISSUE THREAD

**Issue by AishSundar** [cncf/k8s-conformance#221]
As per guidance from Sig-Arch we will focus our Conformance coverage efforts first on areas where functionality can be swapped out by providers, specifically around testing etcd, watch. Towards this we will be working with Sig-API-Machinery to
(i) Add conformance coverage for following 2 scenarios in 1.11 - [PR#63947](https://github.com/kubernetes/kubernetes/pull/63947), [PR#61424](https://github.com/kubernetes/kubernetes/pull/61424)
(ii)Identify API endpoints to prioritize and define meaningful test scenarios / user journeys to automate in 1.12

/cc @jennybuckley @fedebongio @jagosan @timothysc @mithrav
/sig api-machinery

**Comment by AishSundar** [comment]
Tracking sheet - https://docs.google.com/spreadsheets/d/1p_xzVmK4uKC8oh1UBgXVcqGHC1YaYrppn55KrcgUyMk/edit#gid=0

**Comment by AishSundar** [comment]
Working with Api-machinery SIG offline (@fedebongio, @jennybuckley), they have identified the following existing e2e tests to be promoted to conformance suite ([Tracker sheet](https://docs.google.com/spreadsheets/d/1p_xzVmK4uKC8oh1UBgXVcqGHC1YaYrppn55KrcgUyMk/edit#gid=0)).

* [sig-api-machinery] Aggregator Should be able to support the 1.7 Sample API Server using the current Aggregator (already in progress in 1.11)
* [sig-api-machinery] Garbage collector should delete jobs and pods created by cronjob
* [sig-api-machinery] Garbage collector should orphan pods created by rc if deleteOptions.OrphanDependents is nil
* [sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted.
* [sig-api-machinery] Namespaces [Serial] should ensure that all services are removed when a namespace is deleted.
* [sig-api-machinery] Servers with support for API chunking should return chunks of results for list calls

As next steps, 
* Globant vendors will be running these tests to ensure they pass flakiness criteria, do not skip providers etc
* Globant vendors will be creating PRs to promote these cases to Conformance and get initial review from Api-machinery SIG, before looping in Sig-Architecture for review.

/cc @mgdevstack

**Comment by AishSundar** [comment]
@fedebongio and @WilliamDenniss Need some clarity / guidance on promoting / rewriting the following e2e tests
* https://github.com/kubernetes/kubernetes/issues/65427
* https://github.com/kubernetes/kubernetes/issues/65428

**Comment by hh** [comment]
/close
I think this issue is stale.
