### ISSUE TITLE
Add contact email as requiement for PRODUCT.yaml with Conformance submissions

### ISSUE THREAD

**Issue by Riaankl** [cncf/k8s-conformance#2251]
- Added contact email address as a [requiement for PRODUCT.yaml](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml)
- Add check for email address to CNCF-CI bot check
- Update the list of CNCF-CI [Requiements](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements)

Explanation should be given that the email address would be use in case of any allerts round the Conformance certifcation process or changes that might affect the functioning of the conformance testing.

**Comment by BobyMCbobs** [comment]
This will be quite straight-forward. Email validation will also be a helpful thing to have, so I'll rework the _the URL fields in the PRODUCT.yaml are valid URLs_ scenario to support both.

**Comment by BobyMCbobs** [comment]
PR: https://github.com/cncf/k8s-conformance/pull/2255

**Comment by Riaankl** [comment]
Proof to work effectively in the cncf/k8s-conformance repo
