### ISSUE TITLE
Scrap commit email addresses for CNCF/K8s-Conformance for Conformance submissions for release 1.23-1.25 

### ISSUE THREAD

**Issue by Riaankl** [cncf/k8s-conformance#2254]
We need the email addressses for sending out an Conformance change alert as discussed in [Slack](https://kubernetes.slack.com/archives/C78F00H99/p1667421895575939)

**Comment by BobyMCbobs** [comment]
There appears to be 153 commiters on v1.2{3,4,5} releases. 60 of which have noreply.github.com email address, to ignore or note.

**Comment by Riaankl** [comment]
Good job, thanks @BobyMCbobs
