### ISSUE TITLE
Roll out Prow Github actions on cncf/k8s-conformance for test in of /assign of multi github handles

### ISSUE THREAD

**Issue by Riaankl** [cncf/k8s-conformance#2256]
Why:
- Test PGA in a working repo
- support K8s-Conformance project with a [request.](https://kubernetes.slack.com/archives/C78F00H99/p1667422065666329)

**Comment by RobertKielty** [comment]
According to this the max number of assignees in an issue us 10 https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users

**Comment by Riaankl** [comment]
https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/about-notifications

`@mentioned` might be the way forward?

**Comment by Riaankl** [comment]
@dims @smarterclayton

**Comment by Riaankl** [comment]
https://github.com/cncf/k8s-conformance/issues/2253

**Comment by Riaankl** [comment]
To be revisited later
