### ISSUE TITLE
Update reviewing.md

### ISSUE THREAD

**Issue by RobertKielty** [cncf/k8s-conformance#2368]
@Riaankl the reviewing.md in this repo which was kind of used as a specification doc for the prow bot that automates these checks now could probably stand to be updated to reflect the automation implemented by the conformance prow bot. 

At the moment it is being referred to internally as what needs to be done manually to review an incoming PR to k8s-conformance.  

What do you think?

https://github.com/cncf/k8s-conformance/blob/master/reviewing.md

**Comment by Riaankl** [comment]
Good point @RobertKielty 
I know all the steps up to the point where the CNCF-CI bot add all the labels, but not the details of the checks @taylorwaggoner does before merging.
Will sync with her before updating.

**Comment by Riaankl** [comment]
@taylorwaggoner I have copied the file to a [HackMD](https://hackmd.io/mVD3G4RfS0y6Lxv-K-C8Ow) for shared editing.
I can change the Technical Requirements section to refer to the work done by the bot.
If you can please ammend the Policy Requirements & Tasks to Complete After Review section to reflect your current work flow in the HackMD, I will create the PR to update the document.
Would that work for you?

**Comment by taylorwaggoner** [comment]
@Riaankl my process for reviewing hasn't really changed - the steps in Policy Requirements and Tasks to Complete can stay as is

**Comment by Riaankl** [comment]
> @Riaankl my process for reviewing hasn't really changed - the steps in Policy Requirements and Tasks to Complete can stay as is

Thankyou, I will let you know when I am done with the changs in the MD to the Tech Requiements

**Comment by Riaankl** [comment]
Update in https://github.com/cncf/k8s-conformance/pull/2370
