### ISSUE TITLE
panic when running conformance

### ISSUE THREAD

**Issue by AlexDiamanti** [cncf/k8s-conformance#264]
#kubectl logs -f -n sonobuoy sonobuoy

time="2018-07-12T18:06:01Z" level=info msg="Scanning plugins in ./plugins.d (pwd: /)"
time="2018-07-12T18:06:01Z" level=info msg="unknown template type" filename=..2018_07_12_18_05_58.722885278
time="2018-07-12T18:06:01Z" level=info msg="unknown template type" filename=..data
time="2018-07-12T18:06:01Z" level=info msg="Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)"
time="2018-07-12T18:06:01Z" level=info msg="Directory (/etc/sonobuoy/plugins.d) does not exist"
time="2018-07-12T18:06:01Z" level=info msg="Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)"
time="2018-07-12T18:06:01Z" level=info msg="Directory (~/sonobuoy/plugins.d) does not exist"
time="2018-07-12T18:06:01Z" level=info msg="Loading plugin driver Job"
time="2018-07-12T18:06:01Z" level=info msg="Filtering namespaces based on the following regex:.*|sonobuoy"
panic: Get https://10.0.0.1:443/api/v1/namespaces: dial tcp 10.0.0.1:443: i/o timeout

goroutine 1 [running]:
github.com/heptio/sonobuoy/pkg/discovery.FilterNamespaces(0x18ce0c0, 0xc420136b60, 0xc420019e40, 0xb, 0x1, 0xc420019e40, 0xb)
	/go/src/github.com/heptio/sonobuoy/pkg/discovery/utils.go:44 +0x480
github.com/heptio/sonobuoy/pkg/discovery.Run(0x18ce0c0, 0xc420136b60, 0xc4200e68c0, 0x0)
	/go/src/github.com/heptio/sonobuoy/pkg/discovery/discovery.go:77 +0x5c4
github.com/heptio/sonobuoy/cmd/sonobuoy/app.runMaster(0xc4203fa900, 0xc42007bb00, 0x0, 0x4)
	/go/src/github.com/heptio/sonobuoy/cmd/sonobuoy/app/master.go:63 +0x7c
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203fa900, 0xc42007ba00, 0x4, 0x4, 0xc4203fa900, 0xc42007ba00)
	/go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:654 +0x2a2
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19174c0, 0x1, 0x1917940, 0x1917b80)
	/go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:729 +0x2fe
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).Execute(0x19174c0, 0xc420501f70, 0xf3ecd4)
	/go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:688 +0x2b
main.main()
	/go/src/github.com/heptio/sonobuoy/cmd/sonobuoy/main.go:25 +0x2d

K8S: 1.10.5
Docker 1.13.1
OS: CentOS Linux release 7.4.1708

In my setup after upgrading docker 1.12 to 1.13 I had default setting for docker when FORWARDING DROP on all hosts which lead to that error.  So, if you want to repro - apply DROP instead of ACCEPT.

sudo iptables -P FORWARD ACCEPT

**Comment by johnSchnake** [comment]
This issue should be closed; the panic occurs during the query logic which as completely changed since this ticket was created.
