### ISSUE TITLE
Tracking Issue - e2e Conformance Fixes & Enhancements

### ISSUE THREAD

**Issue by timothysc** [cncf/k8s-conformance#27]
This issue exists as a tracking reference for the community to reference on issues related to upstream changes to the e2e tests needed for the conformance effort(s). 

## e2e: Internet connection test should not rely on ICMP achievement
* https://github.com/kubernetes/kubernetes/issues/51145  		
* https://github.com/kubernetes/kubernetes/pull/51287  		
* https://github.com/kubernetes/kubernetes/pull/53381  		
	
## ThirdParty resource e2e test should not be marked as conformance				
* https://github.com/kubernetes/kubernetes/issues/52822  		
* https://github.com/kubernetes/kubernetes/pull/52823

**Comment by WilliamDenniss** [comment]
## Remove hostname label condition in SchedulerPredicates 
https://github.com/kubernetes/kubernetes/pull/49253

**Comment by timothysc** [comment]
## Use in-cluster kubeconfig (Fix in 1.8.3) 
https://github.com/kubernetes/kubernetes/pull/53924

**Comment by pires** [comment]
h3. Replace capacity with allocatable to calculate pod resource
1.8 https://github.com/kubernetes/kubernetes/pull/47628
1.7 https://github.com/kubernetes/kubernetes/pull/54587 (still pending the release 1.7.10!)

**Comment by pires** [comment]
## 1.7.x scheduler predicates test that may violate DNS label rules

bug: https://github.com/kubernetes/kubernetes/issues/55117
fix PR for review: https://github.com/kubernetes/kubernetes/pull/55118

**Comment by WilliamDenniss** [comment]
## Tests make an assumption that the permissions on the /tmp dir have not been altered
fix PR (master): https://github.com/kubernetes/kubernetes/pull/54581

**Comment by selfmanagingresource** [comment]
What's the status of this issue? Should we close it out? It seems like all the dependent issues pointed to in the issue have been close/merged.

**Comment by timothysc** [comment]
Closing, these were done long ago.
