### ISSUE TITLE
Conformance tests failing

### ISSUE THREAD

**Issue by lachie83** [cncf/k8s-conformance#270]
I'm having issues running the conformance tests which appear to be fixed in upstream sonobuoy. 

eg. https://github.com/heptio/sonobuoy/issues/425 https://github.com/heptio/sonobuoy/issues/399

Is master in this repository known to work? I did get it to pass on a 1.9 cluster but NOT 1.10 and 1.11

I'm trying to test conformance on 1.10 and 1.11 clusters.

cc @chuckha @timothysc

**Comment by lachie83** [comment]
Okay thanks. Happy to take it for a test run once you do.

**Comment by timothysc** [comment]
@lachie83 - PR up and we rev'd v0.11.5 today.
