### ISSUE TITLE
Missing conformance docs for 1.10 and 1.11

### ISSUE THREAD

**Issue by spiffxp** [cncf/k8s-conformance#273]
We have https://github.com/cncf/k8s-conformance/blob/master/docs/KubeConformance-1.9.md but not the 1.10 and 1.11 variants.

ref: https://github.com/cncf/k8s-conformance/pull/109

I am interested in how these are generated in whether it can be automated so I'll be taking a crack at this.

**Comment by spiffxp** [comment]
I can't seem to find any docs for how these were generated but I think I found the PR that added the code.  Things are hardcoded.  Generating them today would require some manual hacking around.  I will start there and see how we can iterate

**Comment by timothysc** [comment]
I'm PRing to simplify the instructions.

**Comment by timothysc** [comment]
So this work was originally intended to be autogenerated and published with the main docs for every release.

**Comment by timothysc** [comment]
The IBM folks, namely @brahmaroutu , we're leading that effort.

**Comment by PatrickLang** [comment]
+ v1.13 too

**Comment by hh** [comment]
https://github.com/cncf/k8s-conformance/pull/622

**Comment by hh** [comment]
/close
This is merged!
