### ISSUE TITLE
Missing sonobuoy-conformance.yaml file to test

### ISSUE THREAD

**Issue by thdrnsdk** [cncf/k8s-conformance#289]
Hello 

A few days ago, there was a conformance test deployment file but it was gone.
(https://github.com/cncf/k8s-conformance/blob/master/sonobuoy-conformance.yaml)

So now you do not have a way to run pod without having to build sonobuoy?

**Comment by openstacker** [comment]
Hi @thdrnsdk , the sonobuoy-conformance.yaml has been removed. And now you can use the sonobuoy cli to run the test, see https://github.com/cncf/k8s-conformance/blob/master/instructions.md#running

**Comment by hh** [comment]
/close
This issue is stale.
