### ISSUE TITLE
ClusterRoleBinding required to use Sonobuoy on GKE

### ISSUE THREAD

**Issue by WilliamDenniss** [cncf/k8s-conformance#299]
On GKE, the default permissions don't allow Sonobuoy to be run (you'll get an error when creating the RBAC policies).

First you need to grant the cluster-admin clusterrole to your user: 

```
kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin \
 --user=your.google.cloud.email@example.org
```

Is this the case for other environments? Should these instructions be included in https://github.com/cncf/k8s-conformance/blob/master/instructions.md?

**Comment by johnSchnake** [comment]
This is documented on the Sonobuoy README (https://sonobuoy.io/docs/v0.16.2/#known-issues) but do you know if this is still the case? I had a recent experience with a GKE where I created a cluster and ran Sonobuoy without an issue.

**Comment by hh** [comment]
/close
This issue is stale.
