### ISSUE TITLE
Document `hydrophone` as yet another option for running conformance tests

### ISSUE THREAD

**Issue by dims** [cncf/k8s-conformance#2997]
Can we please add pointers to the hydrophone repo and README.md/docs? https://github.com/kubernetes-sigs/hydrophone

**Comment by heyste** [comment]
@dims  As part of some larger documentation changes for the repo [Hydrophone](https://github.com/cncf/k8s-conformance#hydrophone) is now in the main `README.md`

#3007 still needs to merge and will add it to `instructions.md`

**Comment by dims** [comment]
thanks @heyste
