### ISSUE TITLE
Move Sonobuoy - Kube_Conformance container upstream 

### ISSUE THREAD

**Issue by timothysc** [cncf/k8s-conformance#304]
Ideally we move this into upstream and update tests so the skip list is no longer needed.

**Comment by johnSchnake** [comment]
This has already been done; the upstream image code lives at: https://github.com/kubernetes/kubernetes/tree/master/cluster/images/conformance

And the images published to: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/conformance?gcrImageListsize=30

This ticket can be closed.
