### ISSUE TITLE
Suggestion in the folder structure

### ISSUE THREAD

**Issue by cpanato** [cncf/k8s-conformance#31]
I have a suggestion in the folder structure:
currently, we have this:
- vX.Y/$dir/ 
X.Y refers to the kubernetes major and minor version, and $dir is a short subdirectory name to hold the results for your product. Examples would be `gke` or `openshift`.

In our case, we can support multiple platforms like aws, `gcp, azure, metal...`
My suggestion is to add another level inside $dir to set the platform:

- vX.Y/$dir/$plat
which $plat can be `aws`, `azure`, `vmware`, ...

this is relevant?
thanks!

**Comment by WilliamDenniss** [comment]
It's an interesting idea. I think you should submit for now using the flat structure (e.g. `$dir-$plat`). Let's see how things look once everyone has certified, and if the folders get out of hand, we could look at this idea to add sub-folders.
