### ISSUE TITLE
Automate the generation of the Conformance Document 

### ISSUE THREAD

**Issue by brahmaroutu** [cncf/k8s-conformance#310]
As part of the release process we should generate the conformance document and check it into kubernetes documents

- the release build should trigger a prow plugin to create conformance document
- the generated conformance document should be attached to the release (like a release note)
- the generated document should also be checked under cncf/k8s-conformance/docs (optional)

**Comment by spiffxp** [comment]
We discussed during today's meeting. @brahmaroutu is going to update with a proposal on how to have conformance docs generated as part of the release process.  cc @spiffxp @dims

**Comment by heyste** [comment]
@brahmaroutu  While trying to create the conformance docs for [1.10, 1.12, 1.13, 1.14 and 1.15](https://github.com/cncf/k8s-conformance/pull/622) I ran into a few problems.

- The template for the markdown document is in master which caused issues when checking out other kubernetes versions before creating the docs for that version.

- To generate the document for 1.10 required removing the regex check for [Flaky](https://github.com/kubernetes/kubernetes/blob/b81d30a5b29af4c13ce6251b27766fb258178ca9/test/conformance/walk.go#L47)

**Comment by Riaankl** [comment]
Closed via https://github.com/cncf/k8s-conformance/pull/2293
