### ISSUE TITLE
How to submit conformance test result multiple times based on maintenance version

### ISSUE THREAD

**Issue by gyliu513** [cncf/k8s-conformance#354]
If one Kubernetes release distributed two released based on Kubernetes 1.11, one is based on Kubernetes 1.11.2 and another is based on Kubernetes 1.11.3, then how to submit the conformance test?

Let us say the version is as following format:

```
major.minor.maintenance
```

I found that the conformance test only include version like `major.minor` but if I want to submit conformance test twice with same `major.minor` version but different `maintenance` version, how to proceed this?

**Comment by dankohn** [comment]
Please just submit one conformance test for 1.11 (either 1.11.2 or 1.11.3 is OK). We don't track maintenance releases separately.

**Comment by gyliu513** [comment]
Good, thanks @dankohn
