### ISSUE TITLE
Conformance tests with DenyEscalatingExec failing

### ISSUE THREAD

**Issue by dhemeier** [cncf/k8s-conformance#386]
Hey,

when you created a cluster with the `DenyEscalatingExec` Admission Controller, then you have failing test `[k8s.io] KubeletManagedEtcHosts should test kubelet managed /etc/hosts file [NodeConformance] [Conformance]`

Output Logs:
```
/workspace/anago-v1.12.1-beta.0.52+4ed3216f3ec431/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:699
failed to execute command in pod test-host-network-pod, container busybox-1: pods "test-host-network-pod" is forbidden: cannot exec into or attach to a container using host network
Expected error:
    <*errors.StatusError | 0xc421c81680>: {
        ErrStatus: {
            TypeMeta: {Kind: "Status", APIVersion: "v1"},
            ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
            Status: "Failure",
            Message: "pods \"test-host-network-pod\" is forbidden: cannot exec into or attach to a container using host network",
            Reason: "Forbidden",
            Details: {
                Name: "test-host-network-pod",
                Group: "",
                Kind: "pods",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 403,
        },
    }
    pods "test-host-network-pod" is forbidden: cannot exec into or attach to a container using host network
not to have occurred
/workspace/anago-v1.12.1-beta.0.52+4ed3216f3ec431/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/exec_util.go:104
```
Related Issue on Sonobuoy: https://github.com/heptio/sonobuoy/issues/558
The question I and @andrewrynhard has, is the result still okay for acceptance or need we other solutions to resolve this? Maybe disable Admission controller, run test, enable again?

**Comment by andrewrynhard** [comment]
We are nearing a release of our distro that we would like get certified. Anyone able to give an update on this?

**Comment by bgrant0607** [comment]
That admission policy is deprecated.

https://github.com/kubernetes/kubernetes/pull/72737

**Comment by timothysc** [comment]
If it's planned to be deprecated, should we have removed the conformance label with the deprecation change?  We don't have policy around removing the label...

**Comment by bgrant0607** [comment]
We don't have tests of that plugin. Clusters configured with the plugin
fail. More generally, we don't have a testsuite for roles with restricted
privileges yet.

**Comment by timothysc** [comment]
k, it's pretty clear that this plugin-option will violate some assumptions on behavior and prevents some conformance tests from running.  The reason we don't see this in CI, is it's not enabled in any of the release blocking test suites.   

All documentation points to: "Use of a policy-based admission plugin (like PodSecurityPolicy or a custom admission plugin) which can be targeted at specific users or Namespaces and also protects against creation of overly privileged Pods is recommended instead." 

Closing as the plugin causes issues and has a planned deprecation plan.
