### ISSUE TITLE
Tracking Issue - Conformance Coverage for HostAliases

### ISSUE THREAD

**Issue by brahmaroutu** [cncf/k8s-conformance#434]
This is a place holder to track Conformance Coverage on the Topic. 
This issue should remain open until all related work is accomplished in the k/k repo
This issue will contain analysis of the coverage. Existing tests and additional tests requested with links to those issues/PR's

**Comment by mgdevstack** [comment]
There is only one e2e test which is Conformance, verifying hostAlias Pod Spec behavior.
>[k8s.io] Kubelet when scheduling a busybox Pod with hostAliases should write entries to /etc/hosts [NodeConformance] [Conformance]

**Test Description**: Create a Pod with hostAliases and a container with command to output `/etc/hosts` entries. Pod's logs MUST have matching entries of specified hostAliases to the output of `/etc/hosts` entries.

Seeking SIG's attention on -
1. What can be other edgecase/user scenarios should we consider to write new hostAlias based e2e test?
2. Does it make sense to write new e2e "should be able to update hostAlias entries" emphasising PATCH operation. If this is the case, what should be the standard approach of writing PATCH operations for any e2e.

Note: PATCH operations has least API coverage in Conformance Suite. It is very hard to findout any testcase performing PATCH operation.

**Comment by brahmaroutu** [comment]
Please use the following PR: https://github.com/kubernetes/kubernetes/issues/73426
