### ISSUE TITLE
AKS naming collision

### ISSUE THREAD

**Issue by lachie83** [cncf/k8s-conformance#453]
It looks like in 1.13 conformance that the aks directory name (that was used by Azure Kubernetes Service) prior to 1.13 has now been used by Alauda Kubernetes (AKS). 
Reference:

https://github.com/cncf/k8s-conformance/tree/master/v1.13/aks
https://github.com/cncf/k8s-conformance/tree/master/v1.12/aks
https://github.com/cncf/k8s-conformance/tree/master/v1.11/aks
https://github.com/cncf/k8s-conformance/tree/master/v1.10/aks

I suggest that we prefix the aks with the provider name: eg. azure-aks and alauda-aks. 

cc @taylorwaggoner @jing2uo

**Comment by dankohn** [comment]
That sounds reasonable. If you wouldn't mind opening a PR to do so, I'll approve.

**Comment by WilliamDenniss** [comment]
Another approach is to reserve the namespace for the party who first used it. In this case renaming just ‘alauda-aks‘. That would be how I’d want to see our registration treated if this happened to us.

**Comment by lachie83** [comment]
@dankohn @WilliamDenniss I actually prefer William's approach and have submitted a PR that implements that approach by moving the aks directory under v1.13 to alauda-aks. If we are all in agreement please feel free to merge

**Comment by jing2uo** [comment]
@cimomo

**Comment by cimomo** [comment]
Hi @lachie83 , we can rename our directory as alauda-kubernetes. Could you update your PR to reflect this? Thanks.
