### ISSUE TITLE
the lack of 1.7.10 release is blocking a product from becoming conformant

### ISSUE THREAD

**Issue by pires** [cncf/k8s-conformance#54]
We've worked to identify [an issue in 1.7.x](https://github.com/kubernetes/kubernetes/issues/47627) and [backport a fix that is already available for 1.8.x to 1.7.x](https://github.com/kubernetes/kubernetes/pull/54587). Then, I asked the 1.7 branch release manager when we would have a release and was told it would happen this week, most probably yesterday. I've pinged the same release manager and sig-release over Slack but the former seems missing-in-action and the latter can't seem to unblock the situation.

From a product perspective, we want to be part of the initial batch of 1.7.x conformant solutions and right now we're blocked because of this.

**Comment by dankohn** [comment]
@WilliamDenniss can you please escalate this to SIG architecture. We can possibly make an exception for you in accepting a failing test if the only issue is waiting for a merge.

**Comment by pires** [comment]
Thank you Dan! @smugcloud and/or @spahl should take it from here then.

**Comment by pires** [comment]
FYI 1.7.10 is out now.
