### ISSUE TITLE
conformance test result tar.gz does not contain version.txt

### ISSUE THREAD

**Issue by msohn** [cncf/k8s-conformance#55]
I ran conformance test on 3 kubernetes clusters deployed on AWS, Azure and GCE and consistently the plugins/e2e/results/ folder in the tar archive created by sonobuoy does not contain the version.txt file.

Steps I followed to run the tests:

- create kubernetes cluster, I deployed kubernetes v1.8.2
- run `$ curl -L https://raw.githubusercontent.com/cncf/k8s-conformance/master/sonobuoy-conformance.yaml | kubectl apply -f -` to start the tests
- run `$ k logs -f -n sonobuoy sonobuoy` and wait until it shows "level=info msg="no-exit was specified, sonobuoy is now blocking"
- run `$ kubectl cp sonobuoy/sonobuoy:tmp/sonobuoy/201711031447_sonobuoy_58c39447-19d7-49eb-81a7-5b0ad0bb6de6.tar.gz result.tar.gz` to download the test result
- unpack result.tar.gz
- the archive does not contain a version.txt file but an empty nethealth.txt in ./plugins/e2e/results/:
```bash
$ find .
.
./meta
./meta/config.json
./meta/query-time.json
./meta/run.log
./plugins
./plugins/e2e
./plugins/e2e/results
./plugins/e2e/results/e2e.log
./plugins/e2e/results/junit_01.xml
./plugins/e2e/results/nethealth.txt
./resources
./resources/ns
./resources/ns/default
./resources/ns/kube-public
./resources/ns/kube-system
./resources/ns/sonobuoy
```

**Comment by dankohn** [comment]
@timothysc Could you please comment.

**Comment by timothysc** [comment]
To gather a version for submission simply run: 

`kubectl version > version.txt`  

In 1.8 we added log lines to the e2es on startup that verify the client and server version directly in the e2e results.  

I'll PR a minor instruction update.

**Comment by msohn** [comment]
thanks, this helped

Filed https://github.com/cncf/k8s-conformance/pull/56 with our test results

**Comment by dankohn** [comment]
Resolved with https://github.com/cncf/k8s-conformance/commit/8abd2c1a349e46d01958dff285d733055d4c0f36#diff-22b1984e9055744bcb6b52260dfdfb71
