### ISSUE TITLE
latest version of Sonobuoy does not support v1.15.0

### ISSUE THREAD

**Issue by alanpeng** [cncf/k8s-conformance#630]
Running plugins: e2e, systemd-logs
ERRO[0000] Preflight checks failed                      
ERRO[0000] maximum kubernetes version is 1.14.99, got v1.15.0 

But the question is: How did Microsoft/aks-engine pass the conformance test?

**Comment by kandros** [comment]
I had the same question, I figured out they must have used the flag `--skip-preflight` of Sonobuoy.

I checked the `go` code in sonobuoy to understand if skilling preflight could impact in any way the tests or skip anything but that's not the case, it just check if a namespace name already exists, if the pod networking is working and the k8s version.

I had all the tests pass in using v1.15

**Comment by alanpeng** [comment]
Thank you very much. I will give it a try soon.
