### ISSUE TITLE
Branding Guide link invalid

### ISSUE THREAD

**Issue by CraigSterrett** [cncf/k8s-conformance#672]
The terms and conditions doc https://github.com/cncf/k8s-conformance/blob/master/terms-conditions/Certified_Kubernetes_Terms.md has a link to a "Branding Guide". That link is not valid https://github.com/cncf/artwork/blob/master/kubernetes/certified-kubernetes/certified-kubernetes-brand-guide.pdf
This blocks our ability to fill out the Participation Form

**Comment by dankohn** [comment]
Thanks for pointing that out.
