### ISSUE TITLE
How can I replace the image registry address to my private registry address？

### ISSUE THREAD

**Issue by zhangxingdeppon** [cncf/k8s-conformance#686]
Hi buddy，I want to run "sonobuoy run",but it's not success,
 because the server  in our company can't accesse the image registry address,for example gcr.io;
<pre><code>
Events:
  Type     Reason     Age                From                   Message
  ----     ------     ----               ----                   -------
  Normal   Scheduled  28s                default-scheduler      Successfully assigned heptio-sonobuoy/sonobuoy-e2e-job-dcc218c3d2284cfe to kf-app-40-14
  Warning  Failed     27s                kubelet, kf-app-40-14  Failed to pull image "gcr.io/heptio-images/kube-conformance:v1.13": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on [::1]:53: read udp [::1]:15151->[::1]:53: read: connection refused
  Normal   Pulled     27s                kubelet, kf-app-40-14  Container image "gcr.io/heptio-images/sonobuoy:v0.15.1" already present on machine
  Normal   Created    27s                kubelet, kf-app-40-14  Created container
  Normal   Started    27s                kubelet, kf-app-40-14  Started container
  Normal   BackOff    25s (x2 over 26s)  kubelet, kf-app-40-14  Back-off pulling image "gcr.io/heptio-images/kube-conformance:v1.13"
  Warning  Failed     25s (x2 over 26s)  kubelet, kf-app-40-14  Error: ImagePullBackOff
  Warning  Failed     11s (x2 over 27s)  kubelet, kf-app-40-14  Error: ErrImagePull
  Normal   Pulling    11s (x2 over 27s)  kubelet, kf-app-40-14  pulling image "gcr.io/heptio-images/kube-conformance:v1.13"
  Warning  Failed     11s                kubelet, kf-app-40-14  Failed to pull image "gcr.io/heptio-images/kube-conformance:v1.13": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on [::1]:53: read udp [::1]:17586->[::1]:53: read: connection refused

</code></pre>
so I want to replace it to my private registry address,can you give me some advise? Thanks.
In addition .I also want to change "imagePullPolicy: IfNotPresent" to "imagePullPolicy: IfNotPresent",Thanks

**Comment by dankohn** [comment]
Yes, we understand that the image registry isn't available in China without a VPN. Could you please make an account on slack.k8s.io and ask your question on the #k8s-conformance channel. If you can't use Slack, you can also email your question to cncf-k8s-conformance@lists.cncf.io.

**Comment by zhangxingdeppon** [comment]
> Yes, we understand that the image registry isn't available in China without a VPN. Could you please make an account on slack.k8s.io and ask your question on the #k8s-conformance channel. If you can't use Slack, you can also email your question to [cncf-k8s-conformance@lists.cncf.io](mailto:cncf-k8s-conformance@lists.cncf.io).

ok, it's not the real reason.
because our production environment cannot connect to an external network,just private network；so I must push the relational image push to our private image registry so that application can pull it successesly，but the tool “sonobuoy ” doesn't have related parameters to configue registry address;
and maybe I can send email.LOL,thanks.

**Comment by dankohn** [comment]
It should be possible to use Sonobuoy in an airgapped mode but it would be best to discuss on Slack.

**Comment by zhangxingdeppon** [comment]
> airgapped

okay，Thank you very much.

**Comment by johnSchnake** [comment]
I'm not sure if you found the help you needed on slack, but see the docs at https://sonobuoy.io/docs/v0.16.2/airgap/. It is possible to overwrite the registries used for the tests.

**Comment by zhangxingdeppon** [comment]
okay, thanks very much, I will try it again.
