### ISSUE TITLE
Add kubeadm results?

### ISSUE THREAD

**Issue by luxas** [cncf/k8s-conformance#7]
@timothysc @jbeda @roberthbailey Something to consider doing?

**Comment by timothysc** [comment]
@luxas it's a provider validation of a complete stack... 
So for our quick-start we will upload the sonobuoy results.  /cc @chuckha

**Comment by luxas** [comment]
Ok, sorry, haven't had time to catch up with the final doc. That sounds good to me

**Comment by timothysc** [comment]
I'll close this issue per other comment.
