### ISSUE TITLE
Conformance test fails if Docker is started with --log-driver=journald option.

### ISSUE THREAD

**Issue by vadbluedata** [cncf/k8s-conformance#746]
The [sig-cli] test `Kubectl logs should be able to retrieve and filter logs` fails when Docker is started with `--log-driver=journald` option. The` --limit-bytes` option of the `kubectl logs` command is ignored, and all the pod's log is returned instead of just the expected number of bytes, which causes the test to fail. Everything works ok if Docker is started with `--log-driver=json-file` option. (This is on CentOs 3.10.0-1062.1.2.el7.x86_64 )
@dankohn

**Comment by jdef** [comment]
I've observed the same problem in our test cluster
