### ISSUE TITLE
Prow Job to Automate Verification of Conformance Log Submissions

### ISSUE THREAD

**Issue by hh** [cncf/k8s-conformance#760]
It might help to have some automation around Conformance Log Submissions
- [x] Setup Prow for the CNCF org
  - @cjwagner has the k8s-test-infra creds / @idvoretskyi has the CNCF org creds
  - https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#add-the-webhook-to-github
- [ ] Setup tide tags for cncf/k8s-conformance
- [ ] Setup pre-submit job
- [ ] Generate Complete list of Conformance Tests within this repo - kubernetes/kubernetes#84330

The  verification job should:
- [ ] Ensure the correct version of the server is tested
- [ ] Ensure the all Conformance tests have passed by comparing the list of tests for that release to junit.xml

@johnSchnake is looking into using an e2e dry-run reporter combined with the AST walker we use for conformance documentation generation to generate the list of expected tests per release.

/assign @hh

**Comment by hh** [comment]
Ticket for Generating Full List of Tests with metadata and full test names:

https://github.com/kubernetes/kubernetes/issues/84330#issuecomment-548490040

**Comment by hh** [comment]
@idvoretskyi We need to coordinate with @cjwagner to give prow.k8s.io access to the CNCF org as the first step in configuring prow/tide etc.

**Comment by hh** [comment]
/assign @caniszczyk 
Can you work with @idvoretskyi / @cjwagner regarding cncf/org permissions required to setup prow.k8s.io

https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#add-the-webhook-to-github

**Comment by hh** [comment]
/assign @dankohn 

We need to grant @cjwagner temprorary cncf github org admin in order to setup the necessary org <-> prow integrations.

There are secrets on both sides regarding the k8s infra and cncf org event hooks.

We can remove admin rights once the integration is setup.

**Comment by cjwagner** [comment]
CNCF org level webhooks have been configured for prow.k8s.io.

**Comment by hh** [comment]
We will need to migrate the web hooks over to prow.cncf.io when it's brought up.

**Comment by hh** [comment]
@idvoretskyi can you add https://github.com/cncf-ci as an admin to https://github.com/cncf/k8s-conformance. WE'll need this to setup a cncf owned bot for use with prow.cncf.io.

**Comment by idvoretskyi** [comment]
> @idvoretskyi can you add https://github.com/cncf-ci as an admin to https://github.com/cncf/k8s-conformance. WE'll need this to setup a cncf owned bot for use with prow.cncf.io.

This is solved, I assume.
